version: "3.9"

services:
  next-app:
    container_name: next-app
    image: raghuboi/portfolio-website-v2:main
    env_file:
      - .env.production
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    command: --label-enable --http-api-update
    environment:
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_REMOVE_VOLUMES: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8000:8080
    restart: always

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certbot/conf:/etc/letsencrypt:ro
      - ./nginx/certbot/www:/var/www/certbot:ro
    restart: always

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    depends_on:
      - nginx
    command: >-
      certonly --reinstall --webroot --webroot-path=/var/www/certbot
      --email raghunathprabhakar@gmail.com --agree-tos --no-eff-email
      -d dev.raghunathprabhakar.com
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
