version: "3.9"

services:
  next-app:
    container_name: next-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env.local
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: always
    ports:
      - 3000:3000
      - 5555:5555
