version: "3.9"

services:
  next-app:
    container_name: next-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env.local
    volumes:
      - .:/app
      - /app/node_modules
      - /src/db/migrations
    restart: always
    ports:
      - 3000:3000
      - 5555:5555

  db:
    container_name: db
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
