version: "3.9"

services:
  next-app:
    container_name: next-build
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env.production
    restart: always
    ports:
      - 4000:3000
